image: reactnativecommunity/react-native-android

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - doc
  - release
  - github_release

generate_docs:
  stage: doc
  when: manual
  script:
    - npx typedoc index.ts --skipErrorChecking
    - mv docs $CI_COMMIT_TAG
    - echo "todo, create image with aws CLI installed"
    #- bash pushRefs.sh $CI_COMMIT_TAG  "s3://folia-customer/mapsindoors/reference/react-native/mapbox/${SDK_VERSION}" 
  only:
    - tags

release_sdk:
  stage: release
  script:
    - npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
    - npm pkg get version | tr -d \" | grep -q $CI_COMMIT_TAG
    - npm publish
  when: manual
  only:
    - tags

update_github_repo_google:
  stage: github_release
  when: manual
  before_script:
    - mkdir -p ~/.ssh/
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    - eval $(ssh-agent -s)
    - echo "$GITHUB_DEPLOY_KEY_RN_GOOGLE" | tr -d '\r' | ssh-add -
  script:
    - bash push.sh "react-native-mapsindoors-google-maps" "react-native-mapsindoors-google-maps" "${GITLAB_USER_NAME}" $CI_COMMIT_TAG
  only:
    - tags