// Generated by scripts/GenerateDisplayRules.py
import Foundation

import MapsIndoors
import MapsIndoorsCore

public struct IconSizeStruct: Codable {
    public var width: Int
    public var height: Int
}; extension IconSizeStruct { // Don't want to lose default initializer, so this must be in an extension
    public init(withCGSize: CGSize) {
        height = Int(withCGSize.height)
        width = Int(withCGSize.width)
    }
}

private func doReject(_ reject: RCTPromiseRejectBlock, displayRuleId: String,
                      _file: String = #fileID, _func: String = #function, _line: Int = #line, _col: Int = #column) {
    return doReject(reject, message: "The DisplayRule (id: \"\(displayRuleId)\") cannot be found", _file: _file, _func: _func, _line: _line, _col: _col)
}

@objc(DisplayRule)
public class MPDisplayRuleModule: NSObject {
    @objc static func requiresMainQueueSetup() -> Bool { return false }

    private func getTypeRule(typeName: String) -> MPDisplayRuleType? {
    // TODO: very similar to FLutter code, maybe combine shared functions somewhere
        switch (typeName) {
        case "buildingOutline": // TODO: OutLine?
            return .buildingOutline
        case "selectionHighlight":
            return .selectionHighlight
        case "positionIndicator":
            return .blueDot
        case "main":
            return .main
        case "default":
            return .default
        default:
            return nil
        }
    }

    private func getRule(name: String) -> MPDisplayRule? {
        if let typeRule = getTypeRule(typeName: name) {
            return MPMapsIndoors.shared.displayRuleFor(displayRuleType: typeRule)
        } else if let namedRule = MPMapsIndoors.shared.displayRuleFor(type: name.lowercased()){
            return namedRule
        } else if let loc = MPMapsIndoors.shared.locationWith(locationId: name) {
            return MPMapsIndoors.shared.displayRuleFor(location: loc)!
        } else {
            return nil
        }
    }

    func hexStringFromColor(color: UIColor) -> String {
        // TODO: copy paste from Flutter
        let components = color.cgColor.components
        let r: CGFloat = components?[0] ?? 0.0
        let g: CGFloat = components?[1] ?? 0.0
        let b: CGFloat = components?[2] ?? 0.0

        let hexString = String.init(format: "#%02lX%02lX%02lX", lroundf(Float(r * 255)), lroundf(Float(g * 255)), lroundf(Float(b * 255)))
        return hexString
    }

    enum HexParsingError: Error {
        case invalidHexString(String)
    }
    func colorFromHexString(hex: String) throws -> UIColor? {
        let regex = try! NSRegularExpression(pattern: "^#[0-9A-Fa-f]{6}$|^#[0-9A-Fa-f]{8}$")
        let range = NSRange(location: 0, length: hex.utf16.count)

        if (regex.matches(in: hex, range: range).count == 1) {
            return UIColor(fromHexString: hex)!
        } else {
            throw HexParsingError.invalidHexString(hex)
        }
    }

    func cgSizeFromIconSizeJson(json: String) throws -> CGSize {
        let iconSize: IconSizeStruct = try fromJSON(json)
        return CGSize(width: iconSize.width, height: iconSize.height)
    }

    func iconSizeJsonFromCgSize(size: CGSize) -> String {
        let iconSize = IconSizeStruct(withCGSize: size)
        return toJSON(iconSize)
    }

// End of head

    // Getter isVisible->visible
    @objc public func isVisible(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.visible)
    }

    // Setter setVisible->visible
    @objc public func setVisible(_ displayRuleId: String, value: Bool, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.visible = value

        return resolve(nil)
    }

    // Getter isIconVisible->iconVisible
    @objc public func isIconVisible(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.iconVisible)
    }

    // Setter setIconVisible->iconVisible
    @objc public func setIconVisible(_ displayRuleId: String, value: Bool, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.iconVisible = value

        return resolve(nil)
    }

    // Getter isPolygonVisible->polygonVisible
    @objc public func isPolygonVisible(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.polygonVisible)
    }

    // Setter setPolygonVisible->polygonVisible
    @objc public func setPolygonVisible(_ displayRuleId: String, value: Bool, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.polygonVisible = value

        return resolve(nil)
    }

    // Getter isLabelVisible->labelVisible
    @objc public func isLabelVisible(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.labelVisible)
    }

    // Setter setLabelVisible->labelVisible
    @objc public func setLabelVisible(_ displayRuleId: String, value: Bool, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.labelVisible = value

        return resolve(nil)
    }

    // Getter isModel2DVisible->model2DVisible
    @objc public func isModel2DVisible(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.model2DVisible)
    }

    // Setter setModel2DVisible->model2DVisible
    @objc public func setModel2DVisible(_ displayRuleId: String, value: Bool, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.model2DVisible = value

        return resolve(nil)
    }

    // Getter isWallVisible->wallsVisible
    @objc public func isWallVisible(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.wallsVisible)
    }

    // Setter setWallVisible->wallsVisible
    @objc public func setWallVisible(_ displayRuleId: String, value: Bool, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.wallsVisible = value

        return resolve(nil)
    }

    // Getter isExtrusionVisible->extrusionVisible
    @objc public func isExtrusionVisible(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.extrusionVisible)
    }

    // Setter setExtrusionVisible->extrusionVisible
    @objc public func setExtrusionVisible(_ displayRuleId: String, value: Bool, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.extrusionVisible = value

        return resolve(nil)
    }

    // Getter getZoomFrom->zoomFrom
    @objc public func getZoomFrom(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.zoomFrom)
    }

    // Setter setZoomFrom->zoomFrom
    @objc public func setZoomFrom(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.zoomFrom = value

        return resolve(nil)
    }

    // Getter getZoomTo->zoomTo
    @objc public func getZoomTo(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.zoomTo)
    }

    // Setter setZoomTo->zoomTo
    @objc public func setZoomTo(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.zoomTo = value

        return resolve(nil)
    }

    // Getter getIconUrl->iconURL
    @objc public func getIconUrl(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.iconURL?.absoluteString)
    }

    // Setter setIcon->iconURL
    @objc public func setIcon(_ displayRuleId: String, value: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.iconURL = URL(string: value)

        return resolve(nil)
    }

    // Getter getIconSize->iconSize
    @objc public func getIconSize(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(iconSizeJsonFromCgSize(size: displayRule.iconSize))
    }

    // Setter setIconSize->iconSize
    @objc public func setIconSize(_ displayRuleId: String, value: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        do {
            displayRule.iconSize = try cgSizeFromIconSizeJson(json: value)
        } catch let e {
            return doReject(reject, error: e)
        }

        return resolve(nil)
    }

    // Getter getLabel->label
    @objc public func getLabel(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.label)
    }

    // Setter setLabel->label
    @objc public func setLabel(_ displayRuleId: String, value: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.label = value

        return resolve(nil)
    }

    // Getter getLabelZoomFrom->labelZoomFrom
    @objc public func getLabelZoomFrom(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.labelZoomFrom)
    }

    // Setter setLabelZoomFrom->labelZoomFrom
    @objc public func setLabelZoomFrom(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.labelZoomFrom = value

        return resolve(nil)
    }

    // Getter getLabelZoomTo->labelZoomTo
    @objc public func getLabelZoomTo(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.labelZoomTo)
    }

    // Setter setLabelZoomTo->labelZoomTo
    @objc public func setLabelZoomTo(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.labelZoomTo = value

        return resolve(nil)
    }

    // Getter getLabelMaxWidth->labelMaxWidth
    @objc public func getLabelMaxWidth(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.labelMaxWidth)
    }

    // Setter setLabelMaxWidth->labelMaxWidth
    @objc public func setLabelMaxWidth(_ displayRuleId: String, value: UInt, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.labelMaxWidth = value

        return resolve(nil)
    }

    // Getter getPolygonZoomFrom->polygonZoomFrom
    @objc public func getPolygonZoomFrom(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.polygonZoomFrom)
    }

    // Setter setPolygonZoomFrom->polygonZoomFrom
    @objc public func setPolygonZoomFrom(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.polygonZoomFrom = value

        return resolve(nil)
    }

    // Getter getPolygonZoomTo->polygonZoomTo
    @objc public func getPolygonZoomTo(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.polygonZoomTo)
    }

    // Setter setPolygonZoomTo->polygonZoomTo
    @objc public func setPolygonZoomTo(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.polygonZoomTo = value

        return resolve(nil)
    }

    // Getter getPolygonStrokeWidth->polygonStrokeWidth
    @objc public func getPolygonStrokeWidth(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.polygonStrokeWidth)
    }

    // Setter setPolygonStrokeWidth->polygonStrokeWidth
    @objc public func setPolygonStrokeWidth(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.polygonStrokeWidth = value

        return resolve(nil)
    }

    // Getter getPolygonStrokeColor->polygonStrokeColor
    @objc public func getPolygonStrokeColor(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(hexStringFromColor(color: displayRule.polygonStrokeColor!))
    }

    // Setter setPolygonStrokeColor->polygonStrokeColor
    @objc public func setPolygonStrokeColor(_ displayRuleId: String, value: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        do {
            displayRule.polygonStrokeColor = try colorFromHexString(hex: value)
        } catch let e {
            return doReject(reject, error: e)
        }

        return resolve(nil)
    }

    // Getter getPolygonStrokeOpacity->polygonStrokeOpacity
    @objc public func getPolygonStrokeOpacity(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.polygonStrokeOpacity)
    }

    // Setter setPolygonStrokeOpacity->polygonStrokeOpacity
    @objc public func setPolygonStrokeOpacity(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.polygonStrokeOpacity = value

        return resolve(nil)
    }

    // Getter getPolygonFillColor->polygonFillColor
    @objc public func getPolygonFillColor(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(hexStringFromColor(color: displayRule.polygonFillColor!))
    }

    // Setter setPolygonFillColor->polygonFillColor
    @objc public func setPolygonFillColor(_ displayRuleId: String, value: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        do {
            displayRule.polygonFillColor = try colorFromHexString(hex: value)
        } catch let e {
            return doReject(reject, error: e)
        }

        return resolve(nil)
    }

    // Getter getPolygonFillOpacity->polygonFillOpacity
    @objc public func getPolygonFillOpacity(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.polygonFillOpacity)
    }

    // Setter setPolygonFillOpacity->polygonFillOpacity
    @objc public func setPolygonFillOpacity(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.polygonFillOpacity = value

        return resolve(nil)
    }

    // Getter getWallColor->wallsColor
    @objc public func getWallColor(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(hexStringFromColor(color: displayRule.wallsColor!))
    }

    // Setter setWallColor->wallsColor
    @objc public func setWallColor(_ displayRuleId: String, value: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        do {
            displayRule.wallsColor = try colorFromHexString(hex: value)
        } catch let e {
            return doReject(reject, error: e)
        }

        return resolve(nil)
    }

    // Getter getWallHeight->wallsHeight
    @objc public func getWallHeight(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.wallsHeight)
    }

    // Setter setWallHeight->wallsHeight
    @objc public func setWallHeight(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.wallsHeight = value

        return resolve(nil)
    }

    // Getter getWallZoomFrom->wallsZoomFrom
    @objc public func getWallZoomFrom(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.wallsZoomFrom)
    }

    // Setter setWallZoomFrom->wallsZoomFrom
    @objc public func setWallZoomFrom(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.wallsZoomFrom = value

        return resolve(nil)
    }

    // Getter getWallZoomTo->wallsZoomTo
    @objc public func getWallZoomTo(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.wallsZoomTo)
    }

    // Setter setWallZoomTo->wallsZoomTo
    @objc public func setWallZoomTo(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.wallsZoomTo = value

        return resolve(nil)
    }

    // Getter getExtrusionColor->extrusionColor
    @objc public func getExtrusionColor(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(hexStringFromColor(color: displayRule.extrusionColor!))
    }

    // Setter setExtrusionColor->extrusionColor
    @objc public func setExtrusionColor(_ displayRuleId: String, value: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        do {
            displayRule.extrusionColor = try colorFromHexString(hex: value)
        } catch let e {
            return doReject(reject, error: e)
        }

        return resolve(nil)
    }

    // Getter getExtrusionHeight->extrusionHeight
    @objc public func getExtrusionHeight(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.extrusionHeight)
    }

    // Setter setExtrusionHeight->extrusionHeight
    @objc public func setExtrusionHeight(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.extrusionHeight = value

        return resolve(nil)
    }

    // Getter getExtrusionZoomFrom->extrusionZoomFrom
    @objc public func getExtrusionZoomFrom(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.extrusionZoomFrom)
    }

    // Setter setExtrusionZoomFrom->extrusionZoomFrom
    @objc public func setExtrusionZoomFrom(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.extrusionZoomFrom = value

        return resolve(nil)
    }

    // Getter getExtrusionZoomTo->extrusionZoomTo
    @objc public func getExtrusionZoomTo(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.extrusionZoomTo)
    }

    // Setter setExtrusionZoomTo->extrusionZoomTo
    @objc public func setExtrusionZoomTo(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.extrusionZoomTo = value

        return resolve(nil)
    }

    // Getter getModel2DZoomFrom->model2DZoomFrom
    @objc public func getModel2DZoomFrom(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.model2DZoomFrom)
    }

    // Setter setModel2DZoomFrom->model2DZoomFrom
    @objc public func setModel2DZoomFrom(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.model2DZoomFrom = value

        return resolve(nil)
    }

    // Getter getModel2DZoomTo->model2DZoomTo
    @objc public func getModel2DZoomTo(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.model2DZoomTo)
    }

    // Setter setModel2DZoomTo->model2DZoomTo
    @objc public func setModel2DZoomTo(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.model2DZoomTo = value

        return resolve(nil)
    }

    // Getter getModel2DWidthMeters->model2DWidthMeters
    @objc public func getModel2DWidthMeters(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.model2DWidthMeters)
    }

    // Setter setModel2DWidthMeters->model2DWidthMeters
    @objc public func setModel2DWidthMeters(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.model2DWidthMeters = value

        return resolve(nil)
    }

    // Getter getModel2DHeightMeters->model2DHeightMeters
    @objc public func getModel2DHeightMeters(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.model2DHeightMeters)
    }

    // Setter setModel2DHeightMeters->model2DHeightMeters
    @objc public func setModel2DHeightMeters(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.model2DHeightMeters = value

        return resolve(nil)
    }

    // Getter getModel2DBearing->model2DBearing
    @objc public func getModel2DBearing(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.model2DBearing)
    }

    // Setter setModel2DBearing->model2DBearing
    @objc public func setModel2DBearing(_ displayRuleId: String, value: Double, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.model2DBearing = value

        return resolve(nil)
    }

    // Getter getModel2DModel->model2DModel
    @objc public func getModel2DModel(_ displayRuleId: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        return resolve(displayRule.model2DModel)
    }

    // Setter setModel2DModel->model2DModel
    @objc public func setModel2DModel(_ displayRuleId: String, value: String, resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.model2DModel = value

        return resolve(nil)
    }

// Start of tail

    @objc public func reset(_ displayRuleId: String,resolver resolve: RCTPromiseResolveBlock, rejecter reject: RCTPromiseRejectBlock) {
        guard let displayRule = getRule(name: displayRuleId) else {
            return doReject(reject, displayRuleId: displayRuleId)
        }

        displayRule.reset()

        return resolve(nil)
    }

}
